{"event": "runner_on_unreachable", "pid": 85071, "uuid": "d36a78c0-cced-43d2-90fe-f12fec0790f4", "created": "2022-04-30T19:49:52.046726", "parent_uuid": "9e73ed77-7fb2-6441-1182-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "a8b6a2d4-c46e-40b2-9153-c1c6e7d913d3", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-6441-1182-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-6441-1182-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-30T19:49:52.029745", "end": "2022-04-30T19:49:52.046648", "duration": 0.016903, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "d36a78c0-cced-43d2-90fe-f12fec0790f4"}}