{"uuid": "ae80a42a-6088-4e37-8f1a-061185b34f31", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "82c0ed53-815e-48ec-a9a0-bb6c7dcd7c90", "event": "runner_on_unreachable", "pid": 7623, "created": "2022-04-22T13:33:15.177431", "parent_uuid": "9e73ed77-7fb2-1c78-a86e-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "c60cf600-a0b1-46f0-bc3e-bae17715ff5c", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-1c78-a86e-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-1c78-a86e-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:33:15.160209", "end": "2022-04-22T13:33:15.177341", "duration": 0.017132, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "ae80a42a-6088-4e37-8f1a-061185b34f31"}}