{"uuid": "b58c106c-35bc-4fe3-bafc-d3337e85152e", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "d8185683-814a-468f-babc-a3578a86f1a0", "event": "runner_on_unreachable", "pid": 97831, "created": "2022-05-01T08:35:28.469054", "parent_uuid": "9e73ed77-7fb2-505b-66fa-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "bb1f8400-1176-4a6e-bc29-da655cba5318", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-505b-66fa-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-505b-66fa-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-05-01T08:35:28.448568", "end": "2022-05-01T08:35:28.468987", "duration": 0.020419, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "b58c106c-35bc-4fe3-bafc-d3337e85152e"}}