{"uuid": "ec7f1a00-e96c-4fc0-be28-8239d2c2d545", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "71d3f2f1-9e02-4967-92a3-d6387e3a45e4", "event": "runner_on_unreachable", "pid": 23521, "created": "2022-04-28T18:36:18.446829", "parent_uuid": "9e73ed77-7fb2-2315-da0b-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "6a2e5fdf-f2a7-4aa2-92b6-f98668550e24", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-2315-da0b-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-2315-da0b-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-28T18:36:18.425166", "end": "2022-04-28T18:36:18.446717", "duration": 0.021551, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "ec7f1a00-e96c-4fc0-be28-8239d2c2d545"}}