{"uuid": "0dd519a4-ff72-4abd-a641-162f7cbae972", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "f10ddb5b-c988-48a5-87bc-daae324d2b3e", "event": "runner_on_unreachable", "pid": 9221, "created": "2022-04-22T13:45:35.189541", "parent_uuid": "9e73ed77-7fb2-5a89-c83a-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "27ce5e9f-e51b-491b-a740-e2a92a2bcb7e", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-5a89-c83a-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-5a89-c83a-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:45:35.168926", "end": "2022-04-22T13:45:35.189440", "duration": 0.020514, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "0dd519a4-ff72-4abd-a641-162f7cbae972"}}