{"uuid": "50b4eda0-472b-4e0e-a7c3-cae35aec55ed", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "98a0beed-0e5a-4fa6-a9e8-169d424545fb", "event": "runner_on_unreachable", "pid": 4350, "created": "2022-04-22T13:04:44.699335", "parent_uuid": "9e73ed77-7fb2-5307-e154-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "f7363556-750a-4e98-baa9-f0551d1d3efe", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-5307-e154-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-5307-e154-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:04:44.680665", "end": "2022-04-22T13:04:44.699269", "duration": 0.018604, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "50b4eda0-472b-4e0e-a7c3-cae35aec55ed"}}