{"uuid": "4fcdcab7-99d7-4218-b678-3e684bb346b2", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "5b45b9d3-4e19-4229-a48f-82e62b41e6b6", "event": "runner_on_unreachable", "pid": 6916, "created": "2022-04-22T13:29:07.360338", "parent_uuid": "9e73ed77-7fb2-eb15-8624-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "10708900-438b-4ee4-9ce9-3ee3c10d9c51", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-eb15-8624-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-eb15-8624-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:29:07.342427", "end": "2022-04-22T13:29:07.360276", "duration": 0.017849, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "4fcdcab7-99d7-4218-b678-3e684bb346b2"}}