{"uuid": "0a02be58-42f9-4431-8b19-537b3ecf02c5", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "f633a765-4c20-4dd3-8c91-beec3e29ecf2", "event": "runner_on_unreachable", "pid": 9909, "created": "2022-04-22T13:52:54.889947", "parent_uuid": "9e73ed77-7fb2-1cdf-1f9b-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "1fb23c62-4f18-4efc-9313-fbc1808d0fa2", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-1cdf-1f9b-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-1cdf-1f9b-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:52:54.868874", "end": "2022-04-22T13:52:54.889881", "duration": 0.021007, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "0a02be58-42f9-4431-8b19-537b3ecf02c5"}}