{"uuid": "37b08ea5-7e75-45c9-9b31-fba89651d854", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "8aa62de1-ca45-430e-9ca2-7791cd4e017f", "event": "runner_on_unreachable", "pid": 97991, "created": "2022-05-01T08:36:09.776683", "parent_uuid": "9e73ed77-7fb2-593c-945d-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "b724d28a-a2e8-4c88-9865-083198527a11", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-593c-945d-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-593c-945d-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-05-01T08:36:09.754676", "end": "2022-05-01T08:36:09.776574", "duration": 0.021898, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "37b08ea5-7e75-45c9-9b31-fba89651d854"}}