{"uuid": "7626c1f1-1310-4663-b1de-520b8920f3a6", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "6ff968ce-59a0-4d3a-84b7-ce0fd79a3a2e", "event": "runner_on_unreachable", "pid": 10691, "created": "2022-04-22T14:01:44.603747", "parent_uuid": "9e73ed77-7fb2-c146-ef99-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "b8ed7a34-8727-4bde-8ed8-f450fe198d3d", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-c146-ef99-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-c146-ef99-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T14:01:44.586346", "end": "2022-04-22T14:01:44.603677", "duration": 0.017331, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "7626c1f1-1310-4663-b1de-520b8920f3a6"}}