{"event": "verbose", "uuid": "ab98944a-b20d-4164-97ec-5cff76a22587", "counter": 129, "stdout": "\u001b[0;31mERROR! Invalid extra vars data supplied. '@/Users/devops/data/project/python/pgoops/upload/iac/test2/env/extravars' could not be made into a dictionary\u001b[0m", "start_line": 128, "end_line": 129, "runner_ident": "d758c607-e66d-41e4-b629-c3a32e453851", "created": "2022-04-21T15:55:27.649990"}