{"uuid": "273ca0bf-0ed6-4d4d-8cff-026caaa8fb8f", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "a83f3c75-5240-430e-b9ab-f2f36ffc32df", "event": "runner_on_unreachable", "pid": 4469, "created": "2022-04-22T13:05:11.683627", "parent_uuid": "9e73ed77-7fb2-d707-c2e4-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "8579f3d1-bfc4-4fab-9796-90b756c1eaed", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-d707-c2e4-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-d707-c2e4-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:05:11.663870", "end": "2022-04-22T13:05:11.683540", "duration": 0.01967, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "273ca0bf-0ed6-4d4d-8cff-026caaa8fb8f"}}