{"uuid": "4d491717-3414-4525-a191-9125514ca56a", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "a6e5acc7-531c-4dd1-9560-f4c598fa3597", "event": "runner_on_unreachable", "pid": 6651, "created": "2022-04-22T13:27:49.475797", "parent_uuid": "9e73ed77-7fb2-6400-27a8-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "e6a264af-f35a-443d-bcfd-4115230bb587", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-6400-27a8-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-6400-27a8-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:27:49.458352", "end": "2022-04-22T13:27:49.475703", "duration": 0.017351, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "4d491717-3414-4525-a191-9125514ca56a"}}