{"uuid": "5ad981f1-fe99-4fb7-87a1-14393f24849b", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "cdea9367-f699-462e-8308-f1b836ede749", "event": "runner_on_unreachable", "pid": 6774, "created": "2022-04-22T13:27:59.790156", "parent_uuid": "9e73ed77-7fb2-5d68-88e4-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "96be9d5b-d7e6-4199-9650-4ec1fa60a289", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-5d68-88e4-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-5d68-88e4-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:27:59.766066", "end": "2022-04-22T13:27:59.790071", "duration": 0.024005, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "5ad981f1-fe99-4fb7-87a1-14393f24849b"}}