{"uuid": "e28c07f5-6269-4f11-8766-59e97825a329", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "25809c4f-038c-4b3c-b2fe-a62d3941375e", "event": "runner_on_unreachable", "pid": 98121, "created": "2022-05-01T08:36:45.943674", "parent_uuid": "9e73ed77-7fb2-fb59-2586-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "e088ee54-c0eb-4864-b8ca-e342791b1729", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-fb59-2586-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-fb59-2586-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-05-01T08:36:45.924457", "end": "2022-05-01T08:36:45.943597", "duration": 0.01914, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "e28c07f5-6269-4f11-8766-59e97825a329"}}