{"uuid": "72122355-e19d-4abb-9bea-8aa23e86f977", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "703311b5-efc2-4602-888d-18f2f3f2ca43", "event": "runner_on_unreachable", "pid": 20348, "created": "2022-04-28T17:20:12.119460", "parent_uuid": "9e73ed77-7fb2-62cb-d182-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "92a76d1d-77fc-4ec0-9240-920d1dd95a78", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-62cb-d182-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-62cb-d182-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-28T17:20:12.091610", "end": "2022-04-28T17:20:12.119374", "duration": 0.027764, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "72122355-e19d-4abb-9bea-8aa23e86f977"}}