{"uuid": "c5fd9965-f0fa-4bf4-b6bd-1410f949bb3c", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "caf1ce60-fae0-4e00-a090-b584e98769ec", "event": "runner_on_unreachable", "pid": 7854, "created": "2022-04-22T13:35:20.503101", "parent_uuid": "9e73ed77-7fb2-fbb9-e1f2-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "2c46643a-9dfa-4c59-8d5d-528159e936c6", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-fbb9-e1f2-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-fbb9-e1f2-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:35:20.485385", "end": "2022-04-22T13:35:20.502975", "duration": 0.01759, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "c5fd9965-f0fa-4bf4-b6bd-1410f949bb3c"}}