{"uuid": "129e7558-2a58-442e-868d-1db2156e04e0", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "c1e9aaa3-0917-4521-91dd-e6d1230634be", "event": "runner_on_unreachable", "pid": 9744, "created": "2022-04-22T13:51:31.654058", "parent_uuid": "9e73ed77-7fb2-e92e-4741-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "8e94e1e5-f84d-45c6-80aa-d3d8c3458442", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-e92e-4741-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-e92e-4741-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:51:31.634623", "end": "2022-04-22T13:51:31.653991", "duration": 0.019368, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "129e7558-2a58-442e-868d-1db2156e04e0"}}