{"uuid": "33ec3687-4162-43ea-96c5-b9046d6ca404", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "d225c741-d822-43d2-bf18-b62d94c5be68", "event": "runner_on_unreachable", "pid": 20788, "created": "2022-04-28T17:23:28.661378", "parent_uuid": "9e73ed77-7fb2-fa9c-4ca3-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "be7d6856-faa9-4f5f-bcd7-31631cb52b34", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-fa9c-4ca3-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-fa9c-4ca3-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-28T17:23:28.642130", "end": "2022-04-28T17:23:28.661312", "duration": 0.019182, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "33ec3687-4162-43ea-96c5-b9046d6ca404"}}