{"uuid": "4957f9ec-4540-43fe-a354-d4ced388646b", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "3f953eca-f4e6-45df-ae16-fdb613c595d7", "event": "runner_on_unreachable", "pid": 18935, "created": "2022-04-28T17:08:17.971563", "parent_uuid": "9e73ed77-7fb2-dff2-5134-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "ca77968a-98e4-4cd5-b7d8-43e63a4eb4af", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-dff2-5134-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-dff2-5134-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-28T17:08:17.953896", "end": "2022-04-28T17:08:17.971470", "duration": 0.017574, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "4957f9ec-4540-43fe-a354-d4ced388646b"}}