{"uuid": "6634ca0a-314c-4f6b-9bd9-ccf3b8ec7c91", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "5db1df12-722a-4504-b3ab-dbe0c99ce0c0", "event": "runner_on_unreachable", "pid": 6033, "created": "2022-04-22T13:19:22.305393", "parent_uuid": "9e73ed77-7fb2-e6ab-e5be-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "dd46906a-9649-48e9-b93d-778e92776a7f", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-e6ab-e5be-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-e6ab-e5be-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:19:22.283481", "end": "2022-04-22T13:19:22.305312", "duration": 0.021831, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "6634ca0a-314c-4f6b-9bd9-ccf3b8ec7c91"}}