{"uuid": "1387c881-718f-4e4a-88ae-3b4a6292d117", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "4ff9263a-95ef-4ec8-bac4-43b01d97dc71", "event": "runner_on_unreachable", "pid": 4096, "created": "2022-04-22T13:03:29.825761", "parent_uuid": "9e73ed77-7fb2-afca-af25-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "382a896a-4760-43fc-a978-28f577fcdabf", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-afca-af25-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-afca-af25-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:03:29.799541", "end": "2022-04-22T13:03:29.825678", "duration": 0.026137, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "1387c881-718f-4e4a-88ae-3b4a6292d117"}}