{"uuid": "a6b1e8ac-05f7-4ec2-abd3-17322c9a7a5e", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "b085533e-8b7a-4fac-9368-6a413cbddada", "event": "runner_on_unreachable", "pid": 20574, "created": "2022-04-28T17:21:53.927858", "parent_uuid": "9e73ed77-7fb2-fd16-bcda-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "30704fc7-d1e7-4f13-a96b-d6281780a1f5", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-fd16-bcda-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-fd16-bcda-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-28T17:21:53.907728", "end": "2022-04-28T17:21:53.927729", "duration": 0.020001, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "a6b1e8ac-05f7-4ec2-abd3-17322c9a7a5e"}}