{"uuid": "387cd3cd-5a7b-4ecc-8b35-d4865d24eb22", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "e1484f06-6f15-41ff-917a-36cd8705cace", "event": "runner_on_unreachable", "pid": 6340, "created": "2022-04-22T13:21:57.448115", "parent_uuid": "9e73ed77-7fb2-d8a0-f8f3-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "c71ab7d6-9446-41b5-ba9e-287b87fa7c3b", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-d8a0-f8f3-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-d8a0-f8f3-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:21:57.429226", "end": "2022-04-22T13:21:57.448031", "duration": 0.018805, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "387cd3cd-5a7b-4ecc-8b35-d4865d24eb22"}}