{"uuid": "0a030e42-58d5-4135-951f-7a549146d8c1", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "4aba15db-2aa2-4d6b-8053-172a36459582", "event": "runner_on_unreachable", "pid": 10814, "created": "2022-04-22T14:01:58.524711", "parent_uuid": "9e73ed77-7fb2-8751-cef5-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "b0e3824e-a994-4ff4-be5c-b14d0031d297", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-8751-cef5-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-8751-cef5-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T14:01:58.505070", "end": "2022-04-22T14:01:58.524632", "duration": 0.019562, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "0a030e42-58d5-4135-951f-7a549146d8c1"}}